# Generated by Django 5.0.6 on 2024-06-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_usuario_remove_asistencia_nombre_asistencia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='imagen_capturada',
            field=models.ImageField(blank=True, null=True, upload_to='asistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.usuario'),
        ),
    ]
